# --- !Ups

create table "persons" (
  "id" bigint generated by default as identity(start with 0) not null primary key,
  "name" varchar not null,
  "phoneNumber" varchar not null
);

# --- !Downs

drop table "persons" if exists;
